require:
  - rubocop-rails
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'script/**/*'
    - 'frontend/**/*'
    - 'bin/**/*'
    - 'db/**/*'
Documentation:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/serializers/**/*'
Style/OpenStructUse:
  Enabled: false
